"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Akinom_Configurator.py']
DATA_FILES = ['monika.akmcfg']
OPTIONS = {'iconfile': '/Users/marquiskurt/PycharmProjects/robot-octodollop-fork/icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
