"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['libiconfig.py']
DATA_FILES = ['libitina.chr']
OPTIONS = {'iconfile': '/Users/marquiskurt/PycharmProjects/robot-octodollop-fork/icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
